#!/usr/bin/env python

from marc2bf.converter import M2BFConverter

print()
print()


c = M2BFConverter()
c.load(mrcfile="test/marcxml/016s.xml", filetype="xml")
c.convert()
print(c.serialize('n3').decode("utf-8"))

print()
print()

#c.set_profile("lc")
#c.convert()
#print(c.serialize('n3').decode("utf-8"))